name: CI

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
      - release/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - run: yarn install
      - run: yarn typecheck
      - run: yarn lint:eslint
      - run: yarn lint:prettier
